Repository Kerhotalo/kerhotalo, pull requests merged in 2019-09, with the labels that each got.

#3 Added a license
  LICENSE
Labels: documentation

#42 Search and clubhouse create
  backend/src/actions/clubhouseOperations.js
  backend/src/actions/searchOperations.js
  backend/src/db/models/clubhouseSchema.js
  backend/src/resolvers.js
  backend/src/schema.js
Labels: Backend

#44 Travis configurations added
  .travis.yml
  scripts/docker_push.sh
Labels: Devops
